function errorTest() {
  console.logz('错误测试')
  throw new Error('这是一个error测试')
}